/*
 * File: app/view/CbarTitle.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bdn.view.CbarTitle', {
    extend: 'Ext.container.Container',
    alias: 'widget.cbartitle',

    cls: 'topbar-background',
    height: 42,
    itemId: 'cbarTitle',
    minWidth: 1024,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    margins: '5 0 5 4',
                    height: 39,
                    itemId: 'btnnavcontrol',
                    width: 33,
                    iconCls: 'topbar-btn-navbar',
                    scale: 'medium'
                },
                {
                    xtype: 'container',
                    cls: 'metro-logo-ctn',
                    itemId: 'logo-ctn',
                    margin: '6 0 6 41',
                    width: 162,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    }
                },
                {
                    xtype: 'container',
                    flex: 15,
                    itemId: 'searchcontainer',
                    padding: '0 23 0 0',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'searchbox',
                            padding: '7 0 7 0',
                            style: 'border:none;',
                            fieldStyle: 'border:none;',
                            emptyText: 'Product you wanna find?'
                        },
                        {
                            xtype: 'button',
                            margins: '6 0 6 0',
                            border: '1 1 1 0',
                            cls: 'topbar-btn-search-background ',
                            itemId: 'btnsearch',
                            width: 30,
                            iconCls: 'topbar-btn-search-icon'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'ctnButtons',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            cls: 'topbar-btn market',
                            height: 55,
                            itemId: 'btnMarket',
                            overCls: 'topbar-over market-hover',
                            style: 'border:none;',
                            width: 100,
                            allowDepress: false,
                            enableToggle: true,
                            href: '#!grandmarket',
                            hrefTarget: '_self',
                            pressedCls: 'topbar-pressed market-pressed',
                            text: 'Market    ',
                            toggleGroup: 'topbar'
                        },
                        {
                            xtype: 'button',
                            cls: 'topbar-btn offer',
                            itemId: 'btMoney',
                            overCls: 'topbar-over offer-hover',
                            style: 'border:none;',
                            width: 90,
                            enableToggle: true,
                            href: '#WalletPanel',
                            hrefTarget: '_self',
                            pressedCls: 'topbar-pressed offer-pressed',
                            text: 'Money',
                            toggleGroup: 'topbar'
                        },
                        {
                            xtype: 'button',
                            cls: 'topbar-btn favorite',
                            hidden: true,
                            itemId: 'btnFavorite',
                            overCls: 'topbar-over favorite-hover',
                            style: 'border:none;',
                            width: 110,
                            enableToggle: true,
                            pressedCls: 'topbar-pressed favorite-pressed',
                            text: 'Favorite',
                            toggleGroup: 'topbar'
                        },
                        {
                            xtype: 'button',
                            cls: 'topbar-btn manager',
                            itemId: 'btManage',
                            overCls: 'topbar-over manager-hover',
                            style: 'border:none;',
                            width: 110,
                            enableToggle: true,
                            href: '#MiningPanel',
                            hrefTarget: '_self',
                            pressedCls: 'topbar-pressed manager-pressed',
                            text: 'Manage',
                            toggleGroup: 'topbar'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3,
                    itemId: 'tmpcontainer'
                },
                {
                    xtype: 'container',
                    itemId: 'ctAccount',
                    width: 170,
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'ctGuest',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 30,
                                    itemId: 'btSignIn',
                                    margin: '7 0 0 24',
                                    width: 135,
                                    scale: 'medium',
                                    text: 'Sign In | Sign Up'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            itemId: 'ctUser',
                            items: [
                                {
                                    xtype: 'splitbutton',
                                    height: 30,
                                    itemId: 'btProfile',
                                    margin: '7 0 0 0',
                                    rtl: false,
                                    width: 160,
                                    scale: 'medium',
                                    text: 'Hi, {Username}',
                                    menu: {
                                        xtype: 'menu',
                                        itemId: 'mnUser',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                margin: '10 0 0 0',
                                                href: '#!settings',
                                                hrefTarget: '_self',
                                                text: 'Account Settings'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                href: '#!password',
                                                hrefTarget: '_self',
                                                text: 'Change Password'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                href: '#!social',
                                                hrefTarget: '_self',
                                                text: 'Social Connection'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'meLogout',
                                                margin: '0 0 5 0',
                                                href: '#!grandmarket',
                                                text: 'Log Out'
                                            },
                                            {
                                                xtype: 'menuseparator',
                                                hidden: true,
                                                margin: '0 9 0 9'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                hidden: true,
                                                margin: '5 0 10 0',
                                                href: '#!help',
                                                hrefTarget: '_self',
                                                text: 'Help'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});