/*
 * File: app/view/InvoicePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Bdn.view.InvoicePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.invoicepanel',

    height: 481,
    itemId: 'wPaymentTaker',
    width: 1366,
    resizable: false,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    bodyStyle: 'border:none; background-color: white;',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'ctLeft'
                },
                {
                    xtype: 'container',
                    itemId: 'Main',
                    margin: '10 0 0 0',
                    width: 530,
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'StatusColor',
                            padding: 10,
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'Contant',
                                    margin: 5,
                                    maxWidth: 500,
                                    width: 500,
                                    layout: {
                                        type: 'anchor'
                                    },
                                    items: [
                                        {
                                            xtype: 'component',
                                            html: 'Invoicing',
                                            itemId: 'title',
                                            style: 'font-weight:bold; font-size:2.3em;;'
                                        },
                                        {
                                            xtype: 'container',
                                            itemId: 'ctSummary',
                                            layout: {
                                                type: 'card'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    itemId: 'summary_normalsell',
                                                    layout: {
                                                        type: 'anchor'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            anchor: '100%',
                                                            itemId: 'unitprice',
                                                            style: 'display: inline-table; vertical-align: top;',
                                                            fieldLabel: 'Unit price',
                                                            labelStyle: '; font-weight:bold; font-size:100%;',
                                                            value: '0.850 BTC/ lbs'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            anchor: '100%',
                                                            itemId: 'quantity',
                                                            style: 'display: inline-table; vertical-align: top;',
                                                            fieldLabel: 'Quantity',
                                                            labelStyle: '; font-weight:bold; font-size:100%;',
                                                            value: '5.00 lbs'
                                                        },
                                                        {
                                                            xtype: 'displayfield',
                                                            anchor: '100%',
                                                            itemId: 'subtotal',
                                                            style: 'display: inline-table; vertical-align: top;',
                                                            fieldLabel: 'Total',
                                                            labelStyle: '; font-weight:bold; font-size:100%;',
                                                            value: '4.250 BTC'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'component',
                                            html: 'Please send your payment:',
                                            itemId: 'noticetext',
                                            margin: '10 20 15 0',
                                            style: 'font-size:1.5em;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '77%',
                                            height: 30,
                                            itemId: 'txReceipient',
                                            margin: '10 0 10 0',
                                            width: 262,
                                            fieldLabel: 'Receipient',
                                            labelAlign: 'right',
                                            labelSeparator: ' ',
                                            labelWidth: 188,
                                            name: 'paymentmethodid',
                                            value: 'bit2Le',
                                            fieldStyle: 'text-align:right',
                                            emptyText: 'Select payment method'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '77%',
                                            itemId: 'tdAmountPaid',
                                            fieldLabel: 'Amount to send (BTC)',
                                            labelAlign: 'right',
                                            labelSeparator: ' ',
                                            labelWidth: 188,
                                            value: 4.250,
                                            fieldStyle: 'text-align:right',
                                            hideTrigger: true,
                                            decimalPrecision: 3
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '77%',
                                            itemId: 'lbAmount',
                                            style: 'display: inline-table; vertical-align: top;',
                                            fieldLabel: '~ $',
                                            labelAlign: 'right',
                                            labelSeparator: ' ',
                                            labelStyle: 'font-weight:bold; font-size:150%;',
                                            labelWidth: 188,
                                            value: '{total}',
                                            fieldStyle: 'font-weight:bold; font-size:150%;text-align:right'
                                        },
                                        {
                                            xtype: 'component',
                                            html: 'By clicking Pay Now, you accept the terms and contitions  of the offer ',
                                            itemId: 'agreement',
                                            margin: '0 20 20 0',
                                            style: 'font-size: 1.2em;'
                                        },
                                        {
                                            xtype: 'button',
                                            anchor: '100%',
                                            height: 31,
                                            itemId: 'btPay',
                                            margin: '10 10 0 0',
                                            text: 'Pay Now'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'ctRight',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 68,
                            itemId: 'ctStatus'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 68,
                            itemId: 'ctSpace'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});